// <auto-generated />
namespace JOB.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class servico_plus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servico_plus));
        
        string IMigrationMetadata.Id
        {
            get { return "201705010010562_servico_plus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
