USE [mundoup]
GO

/****** Object:  Table [jobup].[AVALIACAO]    Script Date: 25/04/2017 19:45:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[AVALIACAO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[ID_CLIENTE] [uniqueidentifier] NOT NULL,
	[DT_ULT_AVALIACAO] [datetime] NOT NULL,
	[NOTA] [smallint] NOT NULL,
	[COMENTARIO] [varchar](254) NULL,
 CONSTRAINT [PK_jobup.AVALIACAO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[ID_ESPECIALIDADE] ASC,
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[AVALIACAO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.AVALIACAO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE] FOREIGN KEY([ID_USUARIO], [ID_ESPECIALIDADE])
REFERENCES [jobup].[PERFIL_PROFISSIONAL] ([ID_USUARIO], [ID_ESPECIALIDADE])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[AVALIACAO] CHECK CONSTRAINT [FK_jobup.AVALIACAO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE]
GO


