USE [mundoup]
GO

/****** Object:  Table [jobup].[CONTATO]    Script Date: 25/04/2017 19:44:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[CONTATO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[FIXO] [varchar](14) NULL,
	[CELULAR] [varchar](14) NULL,
	[EMAIL] [varchar](254) NOT NULL,
 CONSTRAINT [PK_jobup.CONTATO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[CONTATO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.CONTATO_jobup.USUARIO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [jobup].[USUARIO] ([ID_USUARIO])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[CONTATO] CHECK CONSTRAINT [FK_jobup.CONTATO_jobup.USUARIO_ID_USUARIO]
GO


