USE [mundoup]
GO

/****** Object:  Table [jobup].[ENDERECO]    Script Date: 25/04/2017 19:44:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[ENDERECO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[UF] [int] NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[LOGRADOURO] [varchar](254) NOT NULL,
	[COMPLEMENTO] [varchar](254) NULL,
	[BAIRRO] [varchar](254) NOT NULL,
	[CIDADE] [varchar](254) NOT NULL,
 CONSTRAINT [PK_jobup.ENDERECO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[ENDERECO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.ENDERECO_jobup.USUARIO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [jobup].[USUARIO] ([ID_USUARIO])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[ENDERECO] CHECK CONSTRAINT [FK_jobup.ENDERECO_jobup.USUARIO_ID_USUARIO]
GO


