USE [mundoup]
GO

/****** Object:  Table [jobup].[ESPECIALIDADE]    Script Date: 05/05/2017 20:16:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[ESPECIALIDADE](
	[ID_ESPECIALIDADE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](254) NOT NULL,
	[EXIGIR_COMPROVACAO] [bit] NOT NULL,
 CONSTRAINT [PK_jobup.ESPECIALIDADE] PRIMARY KEY CLUSTERED 
(
	[ID_ESPECIALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

