USE [mundoup]
GO

/****** Object:  Table [jobup].[FORMACAO]    Script Date: 05/05/2017 20:16:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[FORMACAO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[ID_FORMACAO] [int] NOT NULL,
	[INSTITUICAO] [varchar](254) NOT NULL,
	[NOME_CURSO] [varchar](254) NOT NULL,
	[ANO_FORMACAO] [smallint] NOT NULL,
	[DT_APROVACAO] [datetime] NULL,
	[APROVADO] [bit] NOT NULL,
 CONSTRAINT [PK_jobup.FORMACAO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[ID_ESPECIALIDADE] ASC,
	[ID_FORMACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[FORMACAO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.FORMACAO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE] FOREIGN KEY([ID_USUARIO], [ID_ESPECIALIDADE])
REFERENCES [jobup].[PERFIL_PROFISSIONAL] ([ID_USUARIO], [ID_ESPECIALIDADE])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[FORMACAO] CHECK CONSTRAINT [FK_jobup.FORMACAO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE]
GO

