USE [mundoup]
GO

/****** Object:  Table [jobup].[JOB]    Script Date: 25/04/2017 19:42:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[JOB](
	[ID_JOB] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO_CLIENTE] [uniqueidentifier] NOT NULL,
	[ID_USUARIO_PROFISSIONAL] [uniqueidentifier] NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[DT_JOB] [datetime] NOT NULL,
	[TITULO] [varchar](100) NOT NULL,
	[OBSERVACOES] [varchar](1000) NOT NULL,
	[VALOR_SUGERIDO] [float] NULL,
	[JOB_ACEITO] [bit] NOT NULL,
 CONSTRAINT [PK_jobup.JOB] PRIMARY KEY CLUSTERED 
(
	[ID_JOB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO


