USE [mundoup]
GO

/****** Object:  Table [jobup].[PERFIL_PROFISSIONAL]    Script Date: 05/05/2017 20:17:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[PERFIL_PROFISSIONAL](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[DT_APROVACAO] [datetime] NULL,
	[APROVADO] [bit] NOT NULL,
	[RESUMO_CURRICULO] [varchar](1000) NOT NULL,
 CONSTRAINT [PK_jobup.PERFIL_PROFISSIONAL] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[ID_ESPECIALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[PERFIL_PROFISSIONAL]  WITH CHECK ADD  CONSTRAINT [FK_jobup.PERFIL_PROFISSIONAL_jobup.ESPECIALIDADE_ID_ESPECIALIDADE] FOREIGN KEY([ID_ESPECIALIDADE])
REFERENCES [jobup].[ESPECIALIDADE] ([ID_ESPECIALIDADE])
GO

ALTER TABLE [jobup].[PERFIL_PROFISSIONAL] CHECK CONSTRAINT [FK_jobup.PERFIL_PROFISSIONAL_jobup.ESPECIALIDADE_ID_ESPECIALIDADE]
GO

ALTER TABLE [jobup].[PERFIL_PROFISSIONAL]  WITH CHECK ADD  CONSTRAINT [FK_jobup.PERFIL_PROFISSIONAL_jobup.USUARIO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [jobup].[USUARIO] ([ID_USUARIO])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[PERFIL_PROFISSIONAL] CHECK CONSTRAINT [FK_jobup.PERFIL_PROFISSIONAL_jobup.USUARIO_ID_USUARIO]
GO

