USE [mundoup]
GO

/****** Object:  Table [jobup].[PROPOSTA_SERVICO]    Script Date: 05/05/2017 20:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[PROPOSTA_SERVICO](
	[ID_SERVICO] [uniqueidentifier] NOT NULL,
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[DT_PROPOSTA] [datetime] NOT NULL,
	[VL_PROPOSTA] [float] NOT NULL,
	[JUSTIFICATIVA] [varchar](1000) NULL,
	[ACEITA] [bit] NOT NULL,
	[DURACAO_SERVICO] [int] NOT NULL,
 CONSTRAINT [PK_jobup.PROPOSTA_SERVICO] PRIMARY KEY CLUSTERED 
(
	[ID_SERVICO] ASC,
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[PROPOSTA_SERVICO] ADD  DEFAULT ((0)) FOR [DURACAO_SERVICO]
GO

ALTER TABLE [jobup].[PROPOSTA_SERVICO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.PROPOSTA_SERVICO_jobup.SERVICO_ID_SERVICO] FOREIGN KEY([ID_SERVICO])
REFERENCES [jobup].[SERVICO] ([ID_SERVICO])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[PROPOSTA_SERVICO] CHECK CONSTRAINT [FK_jobup.PROPOSTA_SERVICO_jobup.SERVICO_ID_SERVICO]
GO

ALTER TABLE [jobup].[PROPOSTA_SERVICO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.PROPOSTA_SERVICO_jobup.USUARIO_ID_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [jobup].[USUARIO] ([ID_USUARIO])
GO

ALTER TABLE [jobup].[PROPOSTA_SERVICO] CHECK CONSTRAINT [FK_jobup.PROPOSTA_SERVICO_jobup.USUARIO_ID_USUARIO]
GO

