USE [mundoup]
GO

/****** Object:  Table [jobup].[SERVICO]    Script Date: 01/05/2017 12:01:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[SERVICO](
	[ID_SERVICO] [uniqueidentifier] NOT NULL,
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[ID_SUB_ESPECIALIDADE] [int] NULL,
	[DT_CADASTRO] [datetime] NOT NULL,
	[PUBLICO] [bit] NOT NULL,
	[DS_TITULO] [varchar](256) NOT NULL,
	[DS_OBSERVACOES] [varchar](1000) NULL,
	[VL_SUGERIDO] [float] NULL,
	[TEMPO_SERVICO] [int] NOT NULL,
 CONSTRAINT [PK_jobup.SERVICO] PRIMARY KEY CLUSTERED 
(
	[ID_SERVICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[SERVICO] ADD  DEFAULT ((0)) FOR [TEMPO_SERVICO]
GO

ALTER TABLE [jobup].[SERVICO]  WITH CHECK ADD  CONSTRAINT [FK_jobup.SERVICO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE] FOREIGN KEY([ID_USUARIO], [ID_ESPECIALIDADE])
REFERENCES [jobup].[PERFIL_PROFISSIONAL] ([ID_USUARIO], [ID_ESPECIALIDADE])
ON DELETE CASCADE
GO

ALTER TABLE [jobup].[SERVICO] CHECK CONSTRAINT [FK_jobup.SERVICO_jobup.PERFIL_PROFISSIONAL_ID_USUARIO_ID_ESPECIALIDADE]
GO


