USE [mundoup]
GO

/****** Object:  Table [jobup].[SUB_ESPECIALIDADE]    Script Date: 01/05/2017 12:01:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[SUB_ESPECIALIDADE](
	[ID_SUB_ESPECIALIDADE] [int] IDENTITY(1,1) NOT NULL,
	[ID_ESPECIALIDADE] [int] NOT NULL,
	[DESCRICAO] [varchar](254) NOT NULL,
 CONSTRAINT [PK_jobup.SUB_ESPECIALIDADE] PRIMARY KEY CLUSTERED 
(
	[ID_ESPECIALIDADE] ASC,
	[ID_SUB_ESPECIALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[SUB_ESPECIALIDADE]  WITH CHECK ADD  CONSTRAINT [FK_jobup.SUB_ESPECIALIDADE_jobup.ESPECIALIDADE_ID_ESPECIALIDADE] FOREIGN KEY([ID_ESPECIALIDADE])
REFERENCES [jobup].[ESPECIALIDADE] ([ID_ESPECIALIDADE])
GO

ALTER TABLE [jobup].[SUB_ESPECIALIDADE] CHECK CONSTRAINT [FK_jobup.SUB_ESPECIALIDADE_jobup.ESPECIALIDADE_ID_ESPECIALIDADE]
GO


