USE [mundoup]
GO

/****** Object:  Table [jobup].[USUARIO]    Script Date: 05/05/2017 20:18:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [jobup].[USUARIO](
	[ID_USUARIO] [uniqueidentifier] NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[CPF] [varchar](11) NOT NULL,
	[RG_UF] [int] NOT NULL,
	[RG_NR] [varchar](8) NOT NULL,
	[DT_NASCIMENTO] [datetime] NOT NULL,
	[DT_INCLUSAO] [datetime] NOT NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[DT_APROVACAO] [datetime] NULL,
	[DT_ATIVACAO] [datetime] NULL,
	[DT_ORDENACAO] [datetime] NOT NULL,
	[APROVADO] [bit] NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[BLOQUEADO] [bit] NOT NULL,
	[UF] [int] NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[LOGRADOURO] [varchar](254) NOT NULL,
	[COMPLEMENTO] [varchar](254) NULL,
	[BAIRRO] [varchar](254) NOT NULL,
	[CIDADE] [varchar](254) NOT NULL,
	[FIXO] [varchar](14) NULL,
	[CELULAR] [varchar](14) NULL,
	[EMAIL] [varchar](254) NOT NULL,
 CONSTRAINT [PK_jobup.USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT (newid()) FOR [ID_USUARIO]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ((0)) FOR [BLOQUEADO]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ((0)) FOR [UF]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ('') FOR [CEP]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ('') FOR [LOGRADOURO]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ('') FOR [BAIRRO]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ('') FOR [CIDADE]
GO

ALTER TABLE [jobup].[USUARIO] ADD  DEFAULT ('') FOR [EMAIL]
GO

